# Generated by Django 4.2.4 on 2023-11-11 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventregistration', '0002_remove_order_total_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='ticket_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
