# Generated by Django 4.2.4 on 2023-11-10 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventregistration', '0003_cart_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date',
        ),
    ]
