# Generated by Django 4.2.4 on 2023-11-11 21:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_remove_events_ticketprice_alter_events_capacity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eventregistration', '0004_order_detalhes_order_total_delete_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('endereco_entrega', models.CharField(max_length=200)),
                ('cidade_entrega', models.CharField(max_length=100)),
                ('estado_entrega', models.CharField(max_length=50)),
                ('cep_entrega', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('Concluído', 'Concluído'), ('Em Processamento', 'Em Processamento')], max_length=20)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.events')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
