# Generated by Django 4.2.4 on 2023-11-11 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventregistration', '0005_pedido_delete_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
