# Generated by Django 4.2.4 on 2023-11-28 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventregistration', '0006_pedido_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='datPurchase',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
