# Generated by Django 4.2.4 on 2023-11-28 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventregistration', '0007_pedido_datpurchase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='datPurchase',
            new_name='dataCompra',
        ),
    ]
