# Generated by Django 4.2.4 on 2023-11-28 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_remove_events_ticketprice_alter_events_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
