# Generated by Django 4.2.4 on 2023-09-15 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_alter_user_email_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Qual e-mail você gostaria de utilizar em sua conta?', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(help_text='Sua senha deve possuir pelo menos oito caracteres, incluindo letras maiúsculas e minúsculas e números ', max_length=100),
        ),
    ]
