# Generated by Django 4.2.4 on 2023-12-03 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvaliarEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('descricao', models.TextField()),
                ('qualidade', models.PositiveIntegerField()),
                ('recomendacao', models.BooleanField()),
            ],
        ),
    ]
