# Generated by Django 4.2.4 on 2023-12-03 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_events_status'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliarevento',
            name='evento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='event.events'),
        ),
    ]
